[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "orpl"
version = "v1.0.10c"
authors = [{ name = "Guillaume Sheehy", email = "guillaume.sheehy@polymtl.ca" }]
dependencies = [
  "pyqt5",
  "numpy",
  "scipy",
  "matplotlib",
  "pyperclip",
  "qtmodern",
  "ruamel.yaml<0.18.0",
  "sif-parser",
  "renishawWiRE",
]
description = "Open Raman Processing Library"
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE.md" }

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-cov"
]

[tool.pytest.ini_options]
addopts = "--cov-config=tests/.coveragerc"
markers = [
    "testing: Isolate tests to either check specific functions or tweak the test code without running the entire module.",
    "baseline_removal: Mark a test as part of the baseline_removal module. Its functions filter out noise from input spectra.",
    "calibration: Mark a test as part of the calibration module. Its functions compensate for error caused by system response.",
    "cosmic_ray: Mark a test as part of the cosmic_ray module. Its functions remove cosmic ray spikes from input spectra.",
    "datatypes: Mark a test as part of the datatypes module. Its functions convert data between different formats.",
    "file_io: Mark a test as part of the file_io module. Its functions provide file handling for the ORPL GUI.",
    "metrics: Mark a test as part of the metrics module. Its functions measure the quality of the input data.",
    "normalization: Mark a test as part of the normalization module. Its functions scale spectra to utilize the entire dynamic range of the graph.",
]